### ISSUE TITLE
Bootstrap React App

### ISSUE THREAD

**Issue by worxli** [vochabular/admin-frontend#1]
* [x]  Setup new Create-React-App with Typescript
* [x]  Install Packages: react-router-dom, react-apollo-boost, material-ui
* [x]  Setup Authentifaction with OAuth provider --> Get JWT Token
* [x]  CI/CD including "npm test"
* [x]  Quickstart/Readme

**Comment by dafrie** [comment]
I think we need to discuss JWT auth tomorrow and how exactly we want to implement it.
My suggestion (and how its currently implemented in the bootstrapped react app:

![client-credentials-grant](https://user-images.githubusercontent.com/5886935/53291267-dcd18080-37b0-11e9-9944-f14d2c9fc7c9.png)

So no auth mutations on the backend - the api just checks on each request the validty of the JWT. But I am not sure how compatible this is with the current backend implementation (e.g. Django GraphQL JWT)...

**Comment by dafrie** [comment]
I have added Netlify for our CI/CD needs for now. Hope thats ok. Once we have a fully staging/prod setup I can add the necessary config...
