### ISSUE TITLE
Question: Where do we store user settings?

### ISSUE THREAD

**Issue by dafrie** [vochabular/admin-frontend#22]
Since the user will be able to save some kind of settings such as language etc, we should store that somewhere. Multiple options:

- In the browser's local-storage. Pro: Very easy. Cons: User looses settings when changing device...
- Store it in the Django Backend: Preferred option
- Store it in the Auth0-Backend: Probably not the wisest but doable

Thoughts? Maybe not necessary at all?

**Comment by worxli** [comment]
Option 2

**Comment by YanickSchraner** [comment]
Store user role (admin, viewer, translator, approver, content creator) in auth0
Store settings (user language and translator for which languages) in Django backend

**Comment by dafrie** [comment]
Closed with #37
